package com.example.pizza_point;

import android.app.Dialog;
import android.os.Bundle;


import android.widget.ImageView;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;

public class MainActivity2 extends AppCompatActivity {


    RecyclerView recyclefirst;
    LinearLayoutManager layoutManager;
    ArrayList<First> firsts = new ArrayList<>();
    RecyclerView recyclesecond;
    LinearLayoutManager manager;
    ArrayList<Second> seconds = new ArrayList<>();
    RecyclerView recyclechef;
    LinearLayoutManager chefmanager;
    ArrayList<Chef> chefs = new ArrayList<>();
    ImageView imageView;
     Dialog dialog ;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_main2);
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        recyclefirst = findViewById(R.id.first);
     layoutManager = new LinearLayoutManager(this,LinearLayoutManager.HORIZONTAL,false);
     recyclefirst.setLayoutManager(layoutManager);
        firsts.add(new First(R.drawable.p,"Pizza","4.8","99"," Pizza is an Italian, specifically Neapolitan, dish typically consisting of a flat base of leavened wheat-based dough topped with tomato, cheese, and other ingredients, baked at a high temperature, traditionally in a wood-fired oven.\n" +
                "\n" +
                "The term pizza was first recorded in 997 AD, in a Latin manuscript from the southern Italian town of Gaeta, in Lazio, on the border with Campania.[2] Raffaele Esposito is often credited for creating the modern pizza in Naples.[3][4][5][6] In 2009, Neapolitan pizza[7] was registered with the European Union as a traditional speciality guaranteed (TSG) dish. In 2017, the art of making Neapolitan pizza was included on UNESCO's list of intangible cultural heritage."));
        firsts.add(new First(R.drawable.burger,"Burger","4.0","250","A hamburger, or simply a burger, is a dish consisting of fillings—usually a patty of ground meat, typically beef—placed inside a sliced bun or bread roll. The patties are often served with cheese, lettuce, tomato, onion, pickles, bacon, or chilis with condiments such as ketchup, mustard, mayonnaise, relish or a \"special sauce\", often a variation of Thousand Island dressing, and are frequently placed on sesame seed buns. A hamburger patty topped with cheese is called a cheeseburger.[1] Under some definitions, and in some cultures, a burger is considered a sandwich.\n" +
                "\n" +
                "Hamburgers are typically associated with fast-food ."));
        firsts.add(new First(R.drawable.pasta,"Pasta","3.7","80",")Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking. Pasta was originally only made with durum, although the definition has been expanded to include alternatives for a gluten-free diet, such as rice flour, or legumes such as beans or lentils. Pasta is believed to have developed independently in Italy and is a staple food of Italian cuisine,[1][2] with evidence of Etruscans making pasta as early as 400 BCE in Italy.[3][4]\n" +
                "\n" +
                "Pastas are divided into two broad categories: dried (Italian: pasta secca) and fresh (Italian: pasta fresca)."));
        firsts.add(new First(R.drawable.idle,"Idli","4.2","90"," Idli is a type of savoury rice cake, originating from South India, popular as a breakfast food in Southern India and in Sri Lanka. The cakes are made by steaming a batter consisting of fermented de-husked black lentils and rice. The fermentation process breaks down the starches so that they are more readily metabolised by the body.\n" +
                "\n" +
                "Idli has several variations, including rava idli, which is made from semolina. Regional variants include sanna of Konkan A precursor of the modern idli is mentioned in several ancient Indian works.Vaddaradhane, a 920 CE Kannada language work by Shivakotiacharya, mentions \"iddalige\". "));
        firsts.add(new First(R.drawable.nodel,"Noodle","4.9","100","Noodles are a type of food made from unleavened dough which is either rolled flat and cut, stretched, or extruded, into long strips or strings. Noodles are a staple food in many cultures and made into a variety of shapes. The most common noodles are those derived from either Chinese cuisine or Italian cuisine. Chinese noodles are known by a variety of different names, while Italian noodles are known as pasta.\n" +
                "\n" +
                "While long, thin strips may be the most common, many varieties of noodles are cut into waves, helices, tubes, strings, or shells, or folded over, or cut into other shapes. Noodles are usually cooked in boiling water, sometimes with cooking oil or salt added."));
        firsts.add(new First(R.drawable.pani,"PaniPuri","3.1","30","Panipuri or golgappa is a deep-fried breaded hollow spherical shell - about 1 inch (25 mm) in diameter - filled with a combination of potatoes, raw onions, chickpeas, and spices. It is a common snack and street food in the Indian subcontinent.[2] It is often flavoured with chili powder, chaat masala, herbs, and many other spicesPanipuri has many regional names in the Indian subcontinent:[1][6] Maharashtra and South India: panipuri; Haryana: pani-patashi; Madhya Pradesh: fulki; Uttar Pradesh: pani-ke-batashe/padake; Assam: phuska/puska; Gujarat: pakodi; Odisha: gup-chup; Delhi: golgappa/phuchka; Bengal: phuchka and Bihar: jalpooree/phuchka.Pani puri has evolved significantly over time. Also known as \"golgappa,\" "));
        firsts.add(new First(R.drawable.bhaji,"Pav bhaji","3.5","50","Pav bhaji or pao bhaji (Marathi : पाव भाजी pāʋ bhājī) is a main course and staple food of Mumbai, India, consisting of a thick spicy vegetable curry (bhaji) served with a soft buttered bread roll (pav). It originated in the city of Mumbai, Maharashtra.Pav bhaji is a spiced mixture of mashed vegetables in a thick gravy served with bread. Vegetables in the curry may commonly include potatoes, onions, carrots, chillies, peas, bell peppers and tomatoes. Street sellers usually cook the curry on a flat griddle (tava) and serve the dish hot. A soft white bread roll is the usual accompaniment to the curry, but this does not preclude the use of other bread varieties such as chapati, roti or brown bread.The dish originated as a fast lunch in Mumbai."));
        RecycleFirst adapter = new RecycleFirst(this,firsts);
        recyclefirst.setAdapter(adapter);
        recyclesecond = findViewById(R.id.s);
        manager = new LinearLayoutManager(this,LinearLayoutManager.HORIZONTAL,false);
        recyclesecond.setLayoutManager(manager);
        seconds.add(new Second(R.drawable.chicken,"Chicken Pizza","4.0","250"," Chicken Pizza is an Italian, specifically Neapolitan, dish typically consisting of a flat base of leavened wheat-based dough topped with tomato, cheese, and other ingredients, baked at a high temperature, traditionally in a wood-fired oven.\\n\" +\n" +

                "The term pizza was first recorded in 997 AD, in a Latin manuscript from the southern Italian town of Gaeta, in Lazio, on the border with Campania.[2] Raffaele Esposito is often credited for creating the modern pizza in Naples.[3][4][5][6] In 2009, Neapolitan pizza[7] was registered with the European Union as a traditional speciality guaranteed (TSG) dish. In 2017, the art of making Neapolitan pizza was included on UNESCO's list of intangible cultural heritage"));
        seconds.add(new Second(R.drawable.beef,"Beef Burger","3.8","220","A Beef Burger, or simply a burger, is a dish consisting of fillings—usually a patty of ground meat, typically beef—placed inside a sliced bun or bread roll. The patties are often served with cheese, lettuce, tomato, onion, pickles, bacon, or chilis with condiments such as ketchup, mustard, mayonnaise, relish or a \"special sauce\", often a variation of Thousand Island dressing, and are frequently placed on sesame seed buns. A hamburger patty topped with cheese is called a cheeseburger.[1] Under some definitions, and in some cultures, a burger is considered a sandwich.\nHamburgers are typically associated with fast-food: McDonald's Big Mac and Burger King's Whopper have become global icons of America . "));
        seconds.add(new Second(R.drawable.dosa,"Dosa","2.8","100","A dosa is a thin, savoury crepe in Indian cuisine made from a fermented batter of ground black gram and rice. Dosas are served hot, often with chutney and sambar.The dosa originated in South India, but its precise geographical origins are unknown. According to food historian K. T. Achaya, references in the Sangam literature suggest that dosa was already in use in the ancient Tamil country around the first century CE.[1] However, according to historian P. Thankappan Nair, dosa originated in the town of Udupi in Karnataka.[2] Achaya states that the earliest written mention of dosa appears in the eighth-century literature of present-day Tamil Nadu, while the earliest mention of dosaë in Tulu literature appears a century later."));
        seconds.add(new Second(R.drawable.leg,"Chicken Leg Piece","4.5","200","These chicken legs are golden on the outside, juicy and tender on the inside and unbelievably savory with every bite. With just a few simple ingredients, we turn ordinary chicken drumsticks into extraordinary.Best Damn Chicken Thighs and Brown Rice Best Damn Oven Baked Chicken Quarters Best Damn Oven Baked BBQ Chicken Thighs Best Damn Air Fryer Chicken Legs Best Damn Baked Buffalo Chicken Legs Best Damn Grilled Chicken Legs Best Damn Oven Roasted Chicken Thighs Best Damn Oven Baked Chicken Breast You are here: Home » Chicken Recipes » Best Damn Oven Baked Chicken Legs Best Damn Oven Baked Chicken Legs Last Modified: March 15, 2024 Jump to Recipe·Print Recipe 4.9 from 136 reviewsThese chicken legs. "));
        seconds.add(new Second(R.drawable.biryani,"Mutton Biryani","4.2","300"," Mutton Biryani s a mixed rice dish popular in South Asia, made with rice, meat (chicken, goat, lamb, beef) or seafood (prawns or fish), and spices. To cater to vegetarians, the meat or seafood can be substituted with vegetables or paneer.[1] Sometimes eggs or potatoes are also added.Biryani is one of the most popular dishes among the South Asian diaspora, although the dish is often associated with the region's Muslim population in particular.[3] Similar dishes are also prepared in Iran, Iraq, Myanmar, Thailand, and Malaysia.Biryani is the single most-ordered dish on Indian online food ordering and delivery services, and has been labelled as the most popular dish overall in IndiaThe exact origin of the dish is uncertain, however, it has been suggested."));
        seconds.add(new Second(R.drawable.gulab,"Gulab Jamun","3.2","140","Gulab jamun (also spelled gulaab jamun; lit. 'Rose water berry' or 'Rose berry') is a sweet confectionery or dessert, originating in the Indian subcontinent, and a type of mithai popular in India, Pakistan, Nepal, the Maldives and Bangladesh, as well as Myanmar. It is also common in nations with substantial populations of people with South Asian heritage, such as Mauritius, Fiji, Gulf states, the Malay Peninsula, United Kingdom, United States, Canada, South Africa, and the Caribbean (Jamaica, Trinidad and Tobago, Guyana, Suriname).It is made mainly from milk solids, traditionally from khoya, which is milk reduced to the consistency of a soft dough. Modern recipes call for dried or powdered milk instead of khoya."));
        seconds.add(new Second(R.drawable.chowmein,"Chowmein","4.1","120","Chowmein was introduced from China into the United States by Chinese immigrants who came from the Guangdong provinces in the California gold rush era, bringing their Cantonese style of cooking.In American Chinese cuisine, it is a stir-fried dish consisting of noodles, meat (chicken being most common but pork, beef, shrimp or tofu sometimes being substituted), onions and celery.It is often served as a specific dish at westernized Chinese restaurants. Vegetarian or vegan chow mein is also common.In the American market, two types of chow mein include crispy chow mein and steamed chow mein.The steamed chow mein has a softer texture, while the former is crisper and drier. "));
        seconds.add(new Second(R.drawable.cake,"Chocolate Cake","5","400","This Classic Chocolate Cake is light, moist, rich and delicious that any chocolate lover is going to love it. If you are a beginner, learning to bake, my step by step photo guide and video will help you whip up an easy cake at home. Plus a bonus! I also share an easy buttercream frosting recipe that’s perfectly sweet, light and fluffy You will be surprised to know this is a one bowl and one egg cake that just needs a whisk, no mixer needed except for the frosting. This is our family favorite and makes for a two layered – 6 inch cake that serves 4 to 6 people. Alternately you can make a single layer – 7 or 8 inch cake. It is stable enough to decorate for occasions and celebrations.This tried and tested recipe is adapted from Hershey’s “perfectly chocolate” . "));
        seconds.add(new Second(R.drawable.momos,"Momo's","3.5","90"," Momos are a type of steamed filled dumpling in Tibetan and Nepali cuisine[2] that is also popular in neighbouring Bhutan, Bangladesh, and India. The majority of Tibetan momos are half-moon in shape like jiaozi, while Nepali momos are normally round like baozi. Momos are usually served with a sauce known as achar influenced by the spices and herbs used within many South Asian cuisines. It can also be used in soup, as in jhol momo and mokthukThe earliest Tibetan dumplings were made of highland barley flour as the outer covering, and beef and mutton as the stuffing Momos may be used in soups. Jhol momo (Nepali: झोल मोमो) is a Nepali soup consisting of momos in a spicy vegetable broth called jhol achar."));
        RecycleSecond recycleSecond = new RecycleSecond(this,seconds);
        recyclesecond.setAdapter(recycleSecond);
        recyclechef = findViewById(R.id.chef);
        chefmanager = new LinearLayoutManager(this,LinearLayoutManager.HORIZONTAL,false);
        recyclechef.setLayoutManager(chefmanager);
        chefs.add(new Chef(R.drawable.john,"John"," Hello Guys Welcome To My Profile My Name is John I am Working As a Junior Pizza Chef in The Pizza-Point I am Basically From USA But Currently Living In India I did My Graduation In Hotel Management I have five Year OF  Experienced In Pizza Cook & High Quality Skilled In Following Recipes, Ensuring Food Safety , and Customer Service .Specialized in Southern Cuisine Currently training in Latin American Cuisine Deep experience with pastry and baking Expert in knife work Experienced in leadership, adaptability, and collaboration Education: Institute for Culinary Sciences, NY.Bachelor’s degree in culinary sciences and skills 2010-2012 Awarded ‘student with best menu adjustment’ in inter school culinary project New York High School, NY 2005-2010 Head of the football team . "));
        chefs.add(new Chef(R.drawable.smith,"Smith"," Hello Guys Welcome To My Profile My Name is Smith I am Working As a  Burger Chef in The Pizza-Point I am Basically From New zealand  But Currently Living In India I did My Graduation In Hotel Management I have Two  Year OF  Experienced In Burger Cook & High Quality Skilled In Following Recipes, Ensuring Food Safety , and Customer Service .Specialized in Southern Cuisine Currently training in Latin American Cuisine Deep experience with pastry and baking Expert in knife work Experienced in leadership, adaptability, and collaboration Education: Institute for Culinary Sciences, NY.Bachelor’s degree in culinary sciences and skills 2010-2012 Awarded ‘student with best menu adjustment’ in inter school culinary project New York High School, NY 2005-2010 Head of the Cricket team . "));
        chefs.add(new Chef(R.drawable.micheal,"Micheal"," Hello Guys Welcome To My Profile My Name is Micheal I am Working As a  Dosa  Chef in The Pizza-Point I am Basically From South Africa  But Currently Living In India I did My Graduation In Hotel Management I have one   Year OF  Experienced In Dosa Cook & High Quality Skilled In Following Recipes, Ensuring Food Safety , and Customer Service .Specialized in Southern Cuisine Currently training in Latin American Cuisine Deep experience with pastry and baking Expert in knife work Experienced in leadership, adaptability, and collaboration Education: Institute for Culinary Sciences, NY.Bachelor’s degree in culinary sciences and skills 2010-2012 Awarded ‘student with best menu adjustment’ in inter school culinary project New York High School, NY 2005-2010 Head of the Cricket team . "));
        chefs.add(new Chef(R.drawable.r,"Rashid"," Hello Guys Welcome To My Profile My Name is Rashid I am Working As a  Mutton Biryani  Chef in The Pizza-Point I am Basically From Pakistan  But Currently Living In India I did My Graduation In  Diploma in Hotel Management  I have Four Year  OF  Experienced In Mutton Biryani  Cook & High Quality Skilled In Following Recipes, Ensuring Food Safety , and Customer Service .Specialized in Southern Cuisine Currently training in Latin American Cuisine Deep experience with pastry and baking Expert in knife work Experienced in leadership, adaptability, and collaboration Education: Institute for Culinary Sciences, NY.Bachelor’s degree in culinary sciences and skills 2010-2012 Awarded ‘student with best menu adjustment’ in inter school culinary project New York High School, NY 2005-2010 Head of the Basketball team . "));
        chefs.add(new Chef(R.drawable.peter,"Peter"," Hello Guys Welcome To My Profile My Name is Petter I am Working As a Cake  Chef in The Pizza-Point I am Basically From Australia  But Currently Living In India I did My Graduation In Hotel Management I have Six Month  OF  Experienced In Cake Cook & High Quality Skilled In Following Recipes, Ensuring Food Safety , and Customer Service .Specialized in Southern Cuisine Currently training in Latin American Cuisine Deep experience with pastry and baking Expert in knife work Experienced in leadership, adaptability, and collaboration Education: Institute for Culinary Sciences, NY.Bachelor’s degree in culinary sciences and skills 2010-2012 Awarded ‘student with best menu adjustment’ in inter school culinary project New York High School, NY 2005-2010 Head of the Tennis team . "));
        chefs.add(new Chef(R.drawable.vijay,"Vijay"," Hello Guys Welcome To My Profile My Name is Vijay I am Working As a  Pav Bhaji Chef in The Pizza-Point I am Basically From Pune  But Currently Living In Delhi I did My Graduation In Hotel Management I have Two  Nine Year  OF  Experienced In Pav Bhaji Cook & High Quality Skilled In Following Recipes, Ensuring Food Safety , and Customer Service .Specialized in Southern Cuisine Currently training in Latin American Cuisine Deep experience with pastry and baking Expert in knife work Experienced in leadership, adaptability, and collaboration Education: Institute for Culinary Sciences, NY.Bachelor’s degree in culinary sciences and skills 2010-2012 Awarded ‘student with best menu adjustment’ in inter school culinary project New York High School, NY 2005-2010 Head of the Cricket team . "));
        RecycleChef recycleChef = new RecycleChef(this,chefs);
        recyclechef.setAdapter(recycleChef);
        dialog = new Dialog(this);
        dialog.setContentView(R.layout.dp);
        imageView = findViewById(R.id.profile);
        imageView.setOnClickListener(view -> dialog.show());
    }
}